dependencies:
  - name: kafka
    version: 14.2.5
    repository: '@bitnami'
    condition: kafka.enabled
  - name: prometheus
    version: 14.11.0
    repository: '@prometheus-community'
    condition: prometheus.enabled
  - name: grafana
    version: 7.0.6
    repository: '@bitnami'
    condition: grafana.enabled
  - name: edge-service
    version: 0.1.0
    repository: file://../edge-service
    condition: edge-service.enabled
  - name: friend-service
    version: 0.2.0
    repository: file://../friend-service
    condition: friend-service.enabled
  - name: recommendation-service
    version: 0.1.0
    repository: file://../recommendation-service
    condition: recommendation-service.enabled
  - name: user-service
    version: 0.2.0
    repository: file://../user-service
    condition: user-service.enabled